### PR TITLE
MacOSX Support and Fixes

### LINKED ISSUE #16: Adapt the script for Mac OS X
I assume it should work out of the box, there might need some tweaking to upload .dmg instead of .tar.gz

Also cron or equivalent would need to be configure to build each day.

@ilikenwf can you test it ?

### PR DESCRIPTION
**Pull request by ilikenwf**
Closes #16

### CODE REVIEW

**Comment by ilikenwf** [comment]
Should be good now, unless I have an extra or missing "fi" somewhere...it's late.

**Comment by ilikenwf** [comment]
Ok, this fixes everything on Mac. Let me know if it's good for you too.

**Comment by ilikenwf** [comment]
NOW it's fixed.

**Comment by AntoineTurmel** [comment]
Tested on my x86_64 GNU/Linux Ubuntu server and no problem :) Merging it, and will test later with Windows

**Comment by ilikenwf** [comment]
:+1:

**Pull request merged**
